//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;,
        ///&quot;(AB) Alberta&quot;,0,
        ///&quot;(AL) Alabama&quot;,0,
        ///&quot;(AK) Alaska&quot;,0,
        ///&quot;(AZ) Arizona&quot;,0,
        ///&quot;(AR) Arkansas&quot;,0,
        ///&quot;(BC) British Columbia&quot;,0,
        ///&quot;(CA) California&quot;,0,
        ///&quot;(CO) Colorado&quot;,0,
        ///&quot;(CT) Conneticut&quot;,0,
        ///&quot;(DE) Delaware&quot;,0,
        ///&quot;(FL) Florida&quot;,0,
        ///&quot;(GA) Georgia&quot;,0,
        ///&quot;(HI) Hawaii&quot;,0,
        ///&quot;(ID) Idaho&quot;,0,
        ///&quot;(IL) Illinois&quot;,0,
        ///&quot;(IN) Indiana&quot;,0,
        ///&quot;(IA) Iowa&quot;,0,
        ///&quot;(KS) Kansas&quot;,0,
        ///&quot;(KY) Kentucky&quot;,0,
        ///&quot;(LA) Louisiana&quot;,0,
        ///&quot;(ME) Maine&quot;,0,
        ///&quot;(MA) Massachusetts&quot;,0,
        ///&quot;(MB) Manitoba&quot;,0,
        ///&quot;(MI) Michigan&quot;,0,
        ///&quot;(MN) Minnesota&quot;,0,
        ///&quot;(MS) Miss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SalesReps {
            get {
                return ResourceManager.GetString("SalesReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
