//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesMap.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\sigmatek.net\\Documents\\Employees\\Derek_Antrican\\SalesMap.pdf")]
        public string MapFileLocation {
            get {
                return ((string)(this["MapFileLocation"]));
            }
            set {
                this["MapFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v5.5")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckUpdate {
            get {
                return ((bool)(this["AutoCheckUpdate"]));
            }
            set {
                this["AutoCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendLog {
            get {
                return ((bool)(this["SendLog"]));
            }
            set {
                this["SendLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SigmaNEST Subscription Membership Renewal")]
        public string OffSMRSubject {
            get {
                return ((string)(this["OffSMRSubject"]));
            }
            set {
                this["OffSMRSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<span style=""color: #000000; font-family: calibri; font-size: 11pt""> 
YOUR_NAME<br>
<i>Application Engineer</i><br>
<b>SigmaTEK Systems, LLC</b><br>
Main: 513.595.2002<br>
1445 Kemper Meadow Drive | Cincinnati, Ohio 45240<br>
<a href=""http://www.sigmanest.com"">www.sigmanest.com</a><br>
</span>
<a href=""https://www.sigmanest.com/"" target=""_blank""><img src=""https://www.sigmanest.com/images/email/signature.png"" moz -do-not-send=""true"" border=""0""></a>")]
        public string OffSMRSignature {
            get {
                return ((string)(this["OffSMRSignature"]));
            }
            set {
                this["OffSMRSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"While I was looking over your company overview, I noticed that your company’s maintenance subscription has expired.  We would like to continue working with you and your company, although we would need to get the maintenance subscription renewed.  I have copied your sales representative, {SALESREPNAME}, on this email so that he is aware of the pending renewal as well.  You may contact {SALESREPNAME} through his email address {SALESREPEMAIL} or by calling him directly at {SALESREPPHONE}.<br>
<br>
I would like to remind you of the benefits of having a current maintenance subscription.  Being an “on-maintenance” customer allows you to call or email our Technical Support Team and receive help with SigmaNEST, whether it is setting up your machines with SigmaNEST or helping you resolve a difficult nesting problem.  You also have free access to install any supported release of SigmaNEST, including future releases.  These releases contain new features and fixes to old problems, most of which is reported by our customers.  This allows you to have an influence in how our software develops and changes.<br>
<br>
Thank you for contacting SigmaNEST Technical Support and we look forward to continuing to work with you.  If there is anything that we can do to assist your maintenance renewal, please let us know and we would be happy to assist.<br>
<br>
<br>")]
        public string OffSMRBody {
            get {
                return ((string)(this["OffSMRBody"]));
            }
            set {
                this["OffSMRBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",,,,\r\nBrian Blair,brian.blair@sigmanest.com,513-314-7422,BC:AB:WA:MT:AK,RSM:NW\r\nJ" +
            "ustin Brewer,justin.brewer@sigmanest.com,513-314-8381,VA:WV:DE:MD:PA,RSR:NE\r\nAri" +
            "e Brown,arie.brown@sigmanest.com,513-335-7432,GA:LA:TN:AL:MS:NC:SC,RSM:SE\r\nMatt " +
            "Brubaker,matt.brubaker@sigmanest.com,513-532-3544,IN (N):OH (N),RSM:GL\r\nJason De" +
            "Graeve,jason.degraeve@sigmanest.com,519-831-5774,ON (N):SK:NT:YT:NU,RSM:CND\r\nDon" +
            "nie Dugger,donnie.dugger@sigmanest.com,816-454-0600,KS:MO,RSR:N&ST\r\nJim Elmore,j" +
            "im.elmore@sigmanest.com,513-214-9269,CA (S):NV(S):AZ,RSR:SW\r\nFaber Fields,faber." +
            "fields@sigmanest.com,513-430-2973,IN (S),RSR:GL\r\nJoaquin Gonzales,joaquin.gonzal" +
            "es@sigmanest.com,513-507-7631,CA (N):NV (N),RSR:NW\r\nScott Lindley,scott.lindley@" +
            "sigmanest.com,513-309-1394,OR:ID:UT:CO:WY,RSR:NW\r\nRyan Lustig,ryan.lustig@sigman" +
            "est.com,513-508-4271,ME:VT:NH:MA:CT:RI:NY:PA:NJ,RSM:NE\r\nMike Mizak,mike.mizak@si" +
            "gmanest.com,204-293-9418,MB,RSR:CND\r\nAlbert Otto,albert.otto@sigmanest.com,513-2" +
            "88-2262,MI (S),RSR:GL\r\nJonathan Padial,jonathan.padial@sigmanest.com,513-551-721" +
            "2,KY:OH (S),RSR:GL\r\nSylvain Robidoux,sylvain.robidoux@sigmanest.com,438-401-8686" +
            ",QC:NB:NS:PE:NL,RSR:CND\r\nDave Shifo,david.shifo@sigmanest.com,513-316-4791,IA,RS" +
            "R:N&ST\r\nJandre TerreBlanche,jandre.terreblanche@sigmanest.com,513-595-2025,HI,VP" +
            ":HI\r\nSteve Ties,steve.ties@sigmanest.com,513-214-9831,WI:MI (UP):ND:SD:NE:OK:AR:" +
            "NM:MN,RSM:N&ST\r\nCharlie Vanderzwaag,charlie.vanderzwaag@sigmanest.com,226-971-10" +
            "93,ON (S),RSR:CND\r\nSchalk van Niekerk,schalk.vanniekerk@sigmanest.com,513-317-72" +
            "93,IL,RSR:N&ST\r\nBrian Warburton,brian.warburton@sigmanest.com,513-903-7485,TX (N" +
            "),RSR:N&ST\r\nEthan Wyckoff,ethan.wyckoff@sigmanest.com,513-418-1755,FL,RSR:SE")]
        public string SalesReps {
            get {
                return ((string)(this["SalesReps"]));
            }
            set {
                this["SalesReps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@",,
(AB) Alberta,0,NW
(AL) Alabama,0,SE
(AK) Alaska,0,NW
(AZ) Arizona,0,SW
(AR) Arkansas,0,N&ST
(BC) British Columbia,0,NW
(CA) California,1,NW:SW
(CO) Colorado,0,NW
(CT) Connecticut,0,NE
(DE) Delaware,0,NE
(FL) Florida,0,SE
(GA) Georgia,0,SE
(HI) Hawaii,0,HI
(ID) Idaho,0,NW
(IL) Illinois,0,N&ST
(IN) Indiana,1,GL
(IA) Iowa,0,N&ST
(KS) Kansas,0,N&ST
(KY) Kentucky,0,GL
(LA) Louisiana,0,SE
(ME) Maine,0,NE
(MA) Massachusetts,0,NE
(MB) Manitoba,0,CND
(MD) Maryland,0,NE
(MI) Michigan,1,N&ST:GL
(MN) Minnesota,0,N&ST
(MS) Mississippi,0,SE
(MO) Missouri,0,N&ST
(MT) Montana,0,NW
(NB) New Brunswick,0,CND
(NE) Nebraska,0,N&ST
(NV) Nevada,1,NW:SW
(NH) New Hampshire,0,NE
(NJ) New Jersey,0,NE
(NL) Newfoundland and Labrador,0,CND
(NM) New Mexico,0,N&ST
(NS) Nova Scotia,0,CND
(NT) Northwest Territories,0,CND
(NY) New York,0,NE
(NC) North Carolina,0,SE
(ND) North Dakota,0,N&ST
(NU) Nunavut,0,CND
(OH) Ohio,1,GL
(OK) Oklahoma,0,N&ST
(ON) Ontario,1,CND
(OR) Oregon,0,NW
(PA) Pennsylvania,0,NE
(PE) Prince Edward Island,0,CND
(QC) Quebec,0,CND
(RI) Rhode Island,0,NE
(SC) South Carolina,0,SE
(SD) South Dakota,0,N&ST
(SK) Saskatchewan,0,CND
(TN) Tennessee,0,SE
(TX) Texas,0,N&ST
(UT) Utah,0,NW
(VT) Vermont,0,NE
(VA) Virginia,0,NE
(WA) Washington,0,NW
(WV) West Virginia,0,NE
(WI) Wisconsin,0,N&ST
(WY) Wyoming,0,NW
(YT) Yukon,0,CND")]
        public string Regions {
            get {
                return ((string)(this["Regions"]));
            }
            set {
                this["Regions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<span style=""color: #000000; font-family: calibri; font-size: 11pt""> 
YOUR_NAME<br>
<i>Application Engineer</i><br>
<b>SigmaTEK Systems, LLC</b><br>
Main: 513.595.2002<br>
1445 Kemper Meadow Drive | Cincinnati, Ohio 45240<br>
<a href=""http://www.sigmanest.com"">www.sigmanest.com</a><br>
</span>
<a href=""https://www.sigmanest.com/"" target=""_blank""><img src=""https://www.sigmanest.com/images/email/signature.png"" moz -do-not-send=""true"" border=""0""></a>")]
        public string OffSMRSignatureDefault {
            get {
                return ((string)(this["OffSMRSignatureDefault"]));
            }
            set {
                this["OffSMRSignatureDefault"] = value;
            }
        }
    }
}
